// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: anytls.proto

package anytls

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaddingScheme []byte                 `protobuf:"bytes,1,opt,name=padding_scheme,json=paddingScheme,proto3" json:"padding_scheme,omitempty"`
	// fallback_addr is the TCP address of a real TLS/HTTPS server (e.g.
	// "127.0.0.1:8443") to which unauthenticated connections are proxied. This
	// makes the AnyTLS port indistinguishable from a normal HTTPS endpoint under
	// GFW active probing. When empty, unauthenticated connections are rejected.
	FallbackAddr  string `protobuf:"bytes,2,opt,name=fallback_addr,json=fallbackAddr,proto3" json:"fallback_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_anytls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_anytls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_anytls_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetPaddingScheme() []byte {
	if x != nil {
		return x.PaddingScheme
	}
	return nil
}

func (x *Config) GetFallbackAddr() string {
	if x != nil {
		return x.FallbackAddr
	}
	return ""
}

var File_anytls_proto protoreflect.FileDescriptor

const file_anytls_proto_rawDesc = "" +
	"\n" +
	"\fanytls.proto\x12\x11xray.proxy.anytls\"T\n" +
	"\x06Config\x12%\n" +
	"\x0epadding_scheme\x18\x01 \x01(\fR\rpaddingScheme\x12#\n" +
	"\rfallback_addr\x18\x02 \x01(\tR\ffallbackAddrB/Z-github.com/HenZenKuriRIP/XrayR4u/proxy/anytlsb\x06proto3"

var (
	file_anytls_proto_rawDescOnce sync.Once
	file_anytls_proto_rawDescData []byte
)

func file_anytls_proto_rawDescGZIP() []byte {
	file_anytls_proto_rawDescOnce.Do(func() {
		file_anytls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anytls_proto_rawDesc), len(file_anytls_proto_rawDesc)))
	})
	return file_anytls_proto_rawDescData
}

var file_anytls_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_anytls_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.proxy.anytls.Config
}
var file_anytls_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_anytls_proto_init() }
func file_anytls_proto_init() {
	if File_anytls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anytls_proto_rawDesc), len(file_anytls_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_anytls_proto_goTypes,
		DependencyIndexes: file_anytls_proto_depIdxs,
		MessageInfos:      file_anytls_proto_msgTypes,
	}.Build()
	File_anytls_proto = out.File
	file_anytls_proto_goTypes = nil
	file_anytls_proto_depIdxs = nil
}
